name = "veil-usage-example"
version = "0.1.0"
defaultTargets = ["VeilUsageExample"]

[[require]]
name = "veil"
git = "https://github.com/verse-lab/veil.git"
rev = "main"

[[lean_lib]]
name = "VeilUsageExample"